## Introduction to Pandas

**Pandas is one of the most popular Python libraries for data science, data analysis, and data manipulation. It provides powerful data structures and tools for working with structured data like spreadsheets, CSV files, SQL databases, and JSON.**

### Key
 - Pandas is an open-source library built on top of NumPy.
 - It allows for fast analysis, data cleaning, and preparation.
 - It excels in performance and productivity.
 - It also has built-in visualization features.
 - It can work with data from a wide variety of sources.
 - Clean data (handle missing values and duplicates).
 - Transform data (filter, merge, group, encode).
 - Analyze and visualize.

In [61]:
#pip install pandas

In [11]:
import pandas as pd
pd.__version__

'3.0.3'

### Why Pandas is Important in Data Science

 - Cleans messy datasets quickly.
 - Simplifies exploratory data analysis (EDA).
 - Integrates well with libraries like NumPy, Matplotlib, Seaborn, and scikit-learn.
 - Enables efficient preprocessing before building machine learning models.

# • Series

A Series is a one-dimensional labeled array in Pandas.\
**A Series contains:** 
 - **Values** — the actual data
 - **Index** — labels used to identify each value

In [13]:
import pandas as pd
import numpy as np

In [16]:
# creating a series

dat=[10,20,30,40,50]
pd.Series(dat)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [17]:
labels=["a","b","c","d","e"]

In [19]:
print(pd.Series(data=dat,index=labels))

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [20]:
#or
print(pd.Series(dat,labels)) #both codes are same

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [23]:
#Creating a series from a dictionary

dic={'math':74,'statistics':75,'python':80,'R':90}
ser=pd.Series(dic)
print(ser)

math          74
statistics    75
python        80
R             90
dtype: int64

**⇑ The dictionary keys become the index and the dictionary values become the data.**

In [60]:
#In Pandas Series,you can extract values using both index/labels and positions,but the method depends on what you mean.

#Simple rule:
#.loc[] → use index labels
#.iloc[] → use integer positions

In [25]:
#Accessing Series Values
print(ser["math"])

74

In [35]:
labels

['a', 'b', 'c', 'd', 'e']

In [36]:
s=pd.Series(data=labels)
s

0    a
1    b
2    c
3    d
4    e
dtype: str

In [42]:
s[0]

'a'

In [28]:
ser1=pd.Series([1,2,3,4],['India','Russia','Iran','America'])
print(ser1)

India      1
Russia     2
Iran       3
America    4
dtype: int64

In [31]:
ser1['India']

np.int64(1)

In [33]:
ser2=pd.Series([1,2,5,4],['India','Russia','Italy','Saudi'])
ser2

India     1
Russia    2
Italy     5
Saudi     4
dtype: int64

In [54]:
ser1.loc["Iran"]

np.int64(3)

In [52]:
ser1["Iran"]

np.int64(3)

In [55]:
#slicing
ser1[1:3]

Russia    2
Iran      3
dtype: int64

In [59]:
#important attributes
print(ser1.index)
print(ser1.values)
print(ser1.dtype)
print(ser1.size)

Index(['India', 'Russia', 'Iran', 'America'], dtype='str')
[1 2 3 4]
int64
4

In [65]:
#Series operation

#Pandas series Support mathematical operations.

print(ser1)
print(ser2)

India      1
Russia     2
Iran       3
America    4
dtype: int64
India     1
Russia    2
Italy     5
Saudi     4
dtype: int64

In [66]:
ser1+ser2

America    NaN
India      2.0
Iran       NaN
Italy      NaN
Russia     4.0
Saudi      NaN
dtype: float64

In [63]:
ser1-ser2

America    NaN
India      0.0
Iran       NaN
Italy      NaN
Russia     0.0
Saudi      NaN
dtype: float64

In [64]:
ser1*ser2

America    NaN
India      1.0
Iran       NaN
Italy      NaN
Russia     4.0
Saudi      NaN
dtype: float64

In [67]:
ser1/ser2

America    NaN
India      1.0
Iran       NaN
Italy      NaN
Russia     1.0
Saudi      NaN
dtype: float64

In [68]:
sr=pd.Series([10,14,20,30,75])
print(sr)

0    10
1    14
2    20
3    30
4    75
dtype: int64

In [70]:
sr+1

0    11
1    15
2    21
3    31
4    76
dtype: int64

In [71]:
sr-10

0     0
1     4
2    10
3    20
4    65
dtype: int64

In [72]:
sr/2

0     5.0
1     7.0
2    10.0
3    15.0
4    37.5
dtype: float64

In [73]:
#statistical summaries

print(sr)

0    10
1    14
2    20
3    30
4    75
dtype: int64

In [74]:
print(sr.sum())
print(sr.min())
print(sr.max())
print(sr.mean())
print(sr.std())
print(sr.var())

149
10
75
29.8
26.366645596283195
695.2

# • Data Frame (part-1)

**A DataFrame is a 2-dimensional labeled data structure in Pandas that stores data in rows and columns, similar to an Excel spreadsheet or a SQL table.**

 - Each column can have a different data type (integer, float, string, boolean, etc.)
 - Each row has an index (label).
 - Each column has a column name (label).

In [6]:
import numpy as np
import pandas as pd

In [7]:
from numpy.random import randn

In [8]:
np.random.seed(75)

In [64]:
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
#pd.DataFrame(data,index,column)
df

          W         X         Y         Z
A  0.630104 -1.104002  0.541204  1.171178
B -0.309147  0.515890 -0.148269  0.691980
C -1.314389 -0.369113  0.018281  1.421531
D  1.507235 -0.171902 -0.583001 -0.322295
E  1.667252  1.175854  1.752345 -0.004234

In [22]:
#Extracting
df['W']

A   -0.709502
B    0.450415
C    1.346521
D   -0.764168
E   -0.722977
Name: W, dtype: float64

In [12]:
type(df['W'])

pandas.Series

In [13]:
type(df)

pandas.DataFrame

In [14]:
df.W

A   -0.709502
B    0.450415
C    1.346521
D   -0.764168
E   -0.722977
Name: W, dtype: float64

In [23]:
df[['W','Z']]

          W         Z
A -0.709502  1.935981
B  0.450415 -0.178142
C  1.346521  0.509816
D -0.764168 -0.820976
E -0.722977  1.017932

In [25]:
#Rows
df

          W         X         Y         Z
A -0.709502  0.112694  0.477022  1.935981
B  0.450415 -1.188847  0.613631 -0.178142
C  1.346521  1.161150  0.200806  0.509816
D -0.764168 -0.838373  0.584424 -0.820976
E -0.722977 -0.911372  0.714553  1.017932

In [26]:
df.loc['A']

W   -0.709502
X    0.112694
Y    0.477022
Z    1.935981
Name: A, dtype: float64

In [29]:
df.loc['C']  #loc- location label based

W    1.346521
X    1.161150
Y    0.200806
Z    0.509816
Name: C, dtype: float64

In [30]:
df.iloc[2]  #iloc- index based

W    1.346521
X    1.161150
Y    0.200806
Z    0.509816
Name: C, dtype: float64

In [31]:
# above both codes are same,
#If we want to extract with the help location then we use: .loc[' ']
#if you want to extract with the help of index then choose: .iloc[ ]

In [33]:
df.loc['B','Y']   #for extract only one element of the entire data frame.

np.float64(0.613630947923406)

In [35]:
df.loc[['A','B'],['W','Y']]   #subset of the data set

          W         Y
A -0.709502  0.477022
B  0.450415  0.613631

In [68]:
#creating new column
df['new']=np.array([3.0,2.4,5.4,2.1,7.5])

In [54]:
df

          W         X         Y         Z       X+Y  new
A -0.709502  0.112694  0.477022  1.935981  0.589717  3.0
B  0.450415 -1.188847  0.613631 -0.178142 -0.575216  2.4
C  1.346521  1.161150  0.200806  0.509816  1.361956  5.4
D -0.764168 -0.838373  0.584424 -0.820976 -0.253949  2.1
E -0.722977 -0.911372  0.714553  1.017932 -0.196820  7.5

In [39]:
df['X+Y']=df['X']+df["Y"]

In [40]:
df

          W         X         Y         Z  new       X+Y
A -0.709502  0.112694  0.477022  1.935981  3.0  0.589717
B  0.450415 -1.188847  0.613631 -0.178142  2.4 -0.575216
C  1.346521  1.161150  0.200806  0.509816  5.4  1.361956
D -0.764168 -0.838373  0.584424 -0.820976  2.1 -0.253949
E -0.722977 -0.911372  0.714553  1.017932  7.5 -0.196820

In [41]:
#remove column

In [55]:
# .drop(column,axis=1) use for remove column current time.
df.drop('new',axis=1)  # .drop(column,axis=1); axis=1 use for column remove.
                       #  in this command axis=0(by default)

          W         X         Y         Z       X+Y
A -0.709502  0.112694  0.477022  1.935981  0.589717
B  0.450415 -1.188847  0.613631 -0.178142 -0.575216
C  1.346521  1.161150  0.200806  0.509816  1.361956
D -0.764168 -0.838373  0.584424 -0.820976 -0.253949
E -0.722977 -0.911372  0.714553  1.017932 -0.196820

In [56]:
df

          W         X         Y         Z       X+Y  new
A -0.709502  0.112694  0.477022  1.935981  0.589717  3.0
B  0.450415 -1.188847  0.613631 -0.178142 -0.575216  2.4
C  1.346521  1.161150  0.200806  0.509816  1.361956  5.4
D -0.764168 -0.838373  0.584424 -0.820976 -0.253949  2.1
E -0.722977 -0.911372  0.714553  1.017932 -0.196820  7.5

In [69]:
#if you want to remove(drop) permanent column
df.drop('new',axis=1,inplace=True)    # here inplace=True use for permanently remove,by default inplace=False

In [58]:
df

          W         X         Y         Z       X+Y
A -0.709502  0.112694  0.477022  1.935981  0.589717
B  0.450415 -1.188847  0.613631 -0.178142 -0.575216
C  1.346521  1.161150  0.200806  0.509816  1.361956
D -0.764168 -0.838373  0.584424 -0.820976 -0.253949
E -0.722977 -0.911372  0.714553  1.017932 -0.196820

In [59]:
#remove rows

In [66]:
df.drop('E')
df.drop('E',axis=0)
#both codes are same, axis=0 is by default

          W         X         Y         Z
A  0.630104 -1.104002  0.541204  1.171178
B -0.309147  0.515890 -0.148269  0.691980
C -1.314389 -0.369113  0.018281  1.421531
D  1.507235 -0.171902 -0.583001 -0.322295

In [61]:
df

          W         X         Y         Z       X+Y
A -0.709502  0.112694  0.477022  1.935981  0.589717
B  0.450415 -1.188847  0.613631 -0.178142 -0.575216
C  1.346521  1.161150  0.200806  0.509816  1.361956
D -0.764168 -0.838373  0.584424 -0.820976 -0.253949
E -0.722977 -0.911372  0.714553  1.017932 -0.196820

In [70]:
# remove row for permanently
df.drop('E',inplace=True)

In [71]:
df

          W         X         Y         Z
A  0.630104 -1.104002  0.541204  1.171178
B -0.309147  0.515890 -0.148269  0.691980
C -1.314389 -0.369113  0.018281  1.421531
D  1.507235 -0.171902 -0.583001 -0.322295

## • Data Frame (part-2)

In [2]:
import numpy as np
import pandas as pd

In [4]:
from numpy.random import randn

In [6]:
np.random.seed(101)

In [9]:
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

          W         X         Y         Z
A  0.638787  0.329646 -0.497104 -0.754070
B -0.943406  0.484752 -0.116773  1.901755
C  0.238127  1.996652 -0.993263  0.196800
D -1.136645  0.000366  1.025984 -0.156598
E -0.031579  0.649826  2.154846 -0.610259

In [18]:
df>0
#both are the same
booldf=df>0
booldf

       W     X      Y      Z
A   True  True  False  False
B  False  True  False   True
C   True  True  False   True
D  False  True   True  False
E  False  True   True  False

In [21]:
df[booldf]  
#  df[df>0]
#both codes give same output

          W         X         Y         Z
A  0.638787  0.329646       NaN       NaN
B       NaN  0.484752       NaN  1.901755
C  0.238127  1.996652       NaN  0.196800
D       NaN  0.000366  1.025984       NaN
E       NaN  0.649826  2.154846       NaN

In [22]:
df['W']>0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [23]:
#return only true values
df[df['W']>0]

          W         X         Y        Z
A  0.638787  0.329646 -0.497104 -0.75407
C  0.238127  1.996652 -0.993263  0.19680

In [24]:
df[df['Z']<0]

          W         X         Y         Z
A  0.638787  0.329646 -0.497104 -0.754070
D -1.136645  0.000366  1.025984 -0.156598
E -0.031579  0.649826  2.154846 -0.610259

In [28]:
df

          W         X         Y         Z
A  0.638787  0.329646 -0.497104 -0.754070
B -0.943406  0.484752 -0.116773  1.901755
C  0.238127  1.996652 -0.993263  0.196800
D -1.136645  0.000366  1.025984 -0.156598
E -0.031579  0.649826  2.154846 -0.610259

In [29]:
#df[df['W']>0]['X']

#both are same
resdf=df[df['W']>0]
resdf['X']

A    0.329646
C    1.996652
Name: X, dtype: float64

In [31]:
df

          W         X         Y         Z
A  0.638787  0.329646 -0.497104 -0.754070
B -0.943406  0.484752 -0.116773  1.901755
C  0.238127  1.996652 -0.993263  0.196800
D -1.136645  0.000366  1.025984 -0.156598
E -0.031579  0.649826  2.154846 -0.610259

In [38]:
df[df['W']>0][['X','Y']]
#is same as
boolsr=df['W']>0
result=df[boolsr]
mycols=['X','Y']
result[mycols]

          X         Y
A  0.329646 -0.497104
C  1.996652 -0.993263

In [26]:
boolseries=df['W']>0
boolseries

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [39]:
boolseries=df['W']>0
result=df[boolseries]
result

          W         X         Y        Z
A  0.638787  0.329646 -0.497104 -0.75407
C  0.238127  1.996652 -0.993263  0.19680

In [43]:
#conditions
df

          W         X         Y         Z
A  0.638787  0.329646 -0.497104 -0.754070
B -0.943406  0.484752 -0.116773  1.901755
C  0.238127  1.996652 -0.993263  0.196800
D -1.136645  0.000366  1.025984 -0.156598
E -0.031579  0.649826  2.154846 -0.610259

In [45]:
df[(df['W']<0)&(df['Y']>1)]

          W         X         Y         Z
D -1.136645  0.000366  1.025984 -0.156598
E -0.031579  0.649826  2.154846 -0.610259

In [46]:
df[(df['W']>0)|(df['Y']>1)]

          W         X         Y         Z
A  0.638787  0.329646 -0.497104 -0.754070
C  0.238127  1.996652 -0.993263  0.196800
D -1.136645  0.000366  1.025984 -0.156598
E -0.031579  0.649826  2.154846 -0.610259

In [48]:
#index column
df.reset_index()

  index         W         X         Y         Z
0     A  0.638787  0.329646 -0.497104 -0.754070
1     B -0.943406  0.484752 -0.116773  1.901755
2     C  0.238127  1.996652 -0.993263  0.196800
3     D -1.136645  0.000366  1.025984 -0.156598
4     E -0.031579  0.649826  2.154846 -0.610259

In [51]:
newindex='CA NY WY OR CO'.split()

In [52]:
newindex

['CA', 'NY', 'WY', 'OR', 'CO']

In [53]:
df['states']=newindex
df

          W         X         Y         Z states
A  0.638787  0.329646 -0.497104 -0.754070     CA
B -0.943406  0.484752 -0.116773  1.901755     NY
C  0.238127  1.996652 -0.993263  0.196800     WY
D -1.136645  0.000366  1.025984 -0.156598     OR
E -0.031579  0.649826  2.154846 -0.610259     CO

In [54]:
df.set_index('states')

               W         X         Y         Z
states
CA      0.638787  0.329646 -0.497104 -0.754070
NY     -0.943406  0.484752 -0.116773  1.901755
WY      0.238127  1.996652 -0.993263  0.196800
OR     -1.136645  0.000366  1.025984 -0.156598
CO     -0.031579  0.649826  2.154846 -0.610259

## • Data Frame (part-3)

In [55]:
#index levels
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [56]:
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [59]:
dt=pd.DataFrame(randn(6,2),hier_index,['A','B'])
dt

             A         B
G1 1 -0.376519  0.230336
   2  0.681209  1.035125
   3 -0.031160  1.939932
G2 1 -1.005187 -0.741790
   2  0.187125 -0.732845
   3 -1.382920  1.482495

In [60]:
dt.loc['G1']

          A         B
1 -0.376519  0.230336
2  0.681209  1.035125
3 -0.031160  1.939932

In [61]:
dt.loc['G1'].loc[1]

A   -0.376519
B    0.230336
Name: 1, dtype: float64

In [63]:
dt.loc['G1'].loc[2]['B']

np.float64(1.0351250747739213)

In [64]:
dt.index.names=['Group','Numbers']
dt

                      A         B
Group Numbers
G1    1       -0.376519  0.230336
      2        0.681209  1.035125
      3       -0.031160  1.939932
G2    1       -1.005187 -0.741790
      2        0.187125 -0.732845
      3       -1.382920  1.482495

In [66]:
dt.xs('G1')    #cross-section

                A         B
Numbers
1       -0.376519  0.230336
2        0.681209  1.035125
3       -0.031160  1.939932

In [67]:
dt.xs(1,level='Numbers')

              A         B
Group
G1    -0.376519  0.230336
G2    -1.005187 -0.741790

# • Missing Values

**In pandas, missing values represent data that is unavailable or unknown. They are commonly represented as:**

 - NaN (Not a Number) for numeric data
 - None for object/string data

In [1]:
import numpy as np
import pandas as pd

In [3]:
d={'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [4]:
df=pd.DataFrame(d)
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [5]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [6]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [7]:
df.dropna

<bound method DataFrame.dropna of      A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3>

In [9]:
df.dropna(thresh=2)   #returen two rows

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [10]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [11]:
df.fillna(value='FILL VALUE')

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [15]:
df['A'].fillna(value=df['A'].mean())   #extract col A and fill na value by its mean.

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [17]:
df.fillna(value=df['C'].mean())    #fill all NA value by mean of col 'C"

     A    B  C
0  1.0  5.0  1
1  2.0  2.0  2
2  2.0  2.0  3

# • GroupBy

**Groupby allows you to group together rows based off of a column and perform an aggregate function on them.**

**The groupby() method is used to split data into groups based on one or more columns, perform calculations on each group, and combine the results. It is one of the most powerful features of pandas for data analysis.**

In [5]:
data={'Company':['GOOGLE','GOOGLE','MICROSOFT','MICROSOFT','FACEBOOK','FACEBOOK'],
      'Persion':['Sam','Charlie','Amy','Ansh','Carl','Sarah'],
      'Sales':[200,120,340,124,243,350]}

In [6]:
df=pd.DataFrame(data)
df

     Company  Persion  Sales
0     GOOGLE      Sam    200
1     GOOGLE  Charlie    120
2  MICROSOFT      Amy    340
3  MICROSOFT     Ansh    124
4   FACEBOOK     Carl    243
5   FACEBOOK    Sarah    350

In [7]:
df.groupby('Company')

In [11]:
byCompany=df.groupby('Company')

In [12]:
byCompany.sum()

              Persion  Sales
Company
FACEBOOK    CarlSarah    593
GOOGLE     SamCharlie    320
MICROSOFT     AmyAnsh    464

In [15]:
df

     Company  Persion  Sales
0     GOOGLE      Sam    200
1     GOOGLE  Charlie    120
2  MICROSOFT      Amy    340
3  MICROSOFT     Ansh    124
4   FACEBOOK     Carl    243
5   FACEBOOK    Sarah    350

In [18]:
byCompany=df.groupby('Company')
byCompany['Sales'].mean()

Company
FACEBOOK     296.5
GOOGLE       160.0
MICROSOFT    232.0
Name: Sales, dtype: float64

In [20]:
byCompany['Sales'].std()

Company
FACEBOOK      75.660426
GOOGLE        56.568542
MICROSOFT    152.735065
Name: Sales, dtype: float64

In [21]:
byCompany.sum().loc['FACEBOOK']

Persion    CarlSarah
Sales            593
Name: FACEBOOK, dtype: object

In [22]:
byCompany.count()

           Persion  Sales
Company
FACEBOOK         2      2
GOOGLE           2      2
MICROSOFT        2      2

In [23]:
byCompany.max()

          Persion  Sales
Company
FACEBOOK    Sarah    350
GOOGLE        Sam    200
MICROSOFT    Ansh    340

In [24]:
byCompany.min()

           Persion  Sales
Company
FACEBOOK      Carl    243
GOOGLE     Charlie    120
MICROSOFT      Amy    124

In [26]:
byCompany.describe()

          Sales
          count   mean         std    min     25%    50%     75%    max
Company
FACEBOOK    2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOGLE      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MICROSOFT   2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [27]:
byCompany.describe().transpose()

Company        FACEBOOK      GOOGLE   MICROSOFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [32]:
byCompany.describe().transpose()['FACEBOOK']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FACEBOOK, dtype: float64

In [36]:
#or
df.groupby('Company').describe().transpose()['GOOGLE']
#byCompany.describe().transpose()['GOOGLE']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOGLE, dtype: float64